### ISSUE TITLE
npm doesn't resolve fs-extra even though it's in devDeps

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#117]
Well. On a fresh start of boilerplate, I get this error : 

```js
> @ start /home/khoa/web/postcss.org
> cross-env BABEL_ENV=statinamic babel-node scripts/build --server --open --dev

/home/khoa/web/postcss.org/node_modules/statinamic/lib/builder/index.js:21
  _fsExtra2.default.emptyDirSync(destination);
                    ^

TypeError: _fsExtra2.default.emptyDirSync is not a function
    at exports.default (/home/khoa/web/postcss.org/node_modules/statinamic/lib/builder/index.js:21:21)
    at Object.<anonymous> (build.js:12:1)
    at Module._compile (module.js:398:26)
    at loader (/home/khoa/web/postcss.org/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/khoa/web/postcss.org/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at /home/khoa/web/postcss.org/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/home/khoa/web/postcss.org/node_modules/babel-cli/lib/_babel-node.js:162:7)

```

```shell
✔ ~/web/postcss.org [statinamic-0.7 L|✚ 2] 
22:56 $ node -v
v5.3.0
✔ ~/web/postcss.org [statinamic-0.7 L|✚ 2] 
22:56 $ npm -v
3.7.1
```

No idea why npm doesn't resolve fs-extra

**Comment by MoOx** [comment]
Can you try "npm install" again? Just to be sure?
Sometimes I have some deps that are missing that are downloaded after a 2nd npm install... (yeah that sucks).

**Comment by thangngoc89** [comment]
Nope. Run `npm install` again didn't help

**Comment by MoOx** [comment]
I don't want to add a dep for "we don't know why it happens". We need to identify the source of the issue.

**Comment by thangngoc89** [comment]
Alright. Changed the title.

**Comment by thangngoc89** [comment]
This might be an issue with babel (again).

**Comment by MoOx** [comment]
GREAT.

**Comment by MoOx** [comment]
how do you explain this works on travis?
Did you try a full clean npm install one more time, just to be sure?

**Comment by thangngoc89** [comment]
I don't know. Maybe because of your symlink trick ? 

Anyway, this is the log when follow setup guide on homepage
```sh
khoa@khoa-PC-Linux ~/web $ mkdir test
khoa@khoa-PC-Linux ~/web $ cd test
khoa@khoa-PC-Linux ~/web/test $ touch package.json
khoa@khoa-PC-Linux ~/web/test $ npm i https://github.com/thangngoc89/statinamic/archive/fork-master.tar.gz
npm WARN excluding symbolic link .eslintignore -> .gitignore
npm WARN excluding symbolic link docs/.eslintignore -> .gitignore
npm WARN excluding symbolic link .eslintignore -> .gitignore
npm WARN excluding symbolic link docs/.eslintignore -> .gitignore
YOUR-NAME-that-might-be-used-in-some-title-tags@ /home/khoa/web/test
├── UNMET PEER DEPENDENCY babel-cli@^6.3.17
├── UNMET PEER DEPENDENCY babel-core@^6.3.26
├── UNMET PEER DEPENDENCY babel-loader@^6.2.0
├── UNMET PEER DEPENDENCY babel-plugin-webpack-loaders@^0.2.2
├── UNMET PEER DEPENDENCY babel-preset-es2015@^6.3.13
├── UNMET PEER DEPENDENCY babel-preset-react@^6.3.13
├── UNMET PEER DEPENDENCY babel-preset-react-hmre@^1.0.1
├── UNMET PEER DEPENDENCY cross-env@^1.0.7
├── UNMET PEER DEPENDENCY invariant@^2.1.1
├── UNMET PEER DEPENDENCY react@^0.14.0
├── UNMET PEER DEPENDENCY react-dom@^0.14.0
├── UNMET PEER DEPENDENCY react-helmet@^2.1.0
├── UNMET PEER DEPENDENCY react-redux@^4.0.6
├── UNMET PEER DEPENDENCY react-router@^2.0.0-rc6
├── UNMET PEER DEPENDENCY redux@^3.0.0
├── UNMET PEER DEPENDENCY redux-devtools@^3.0.1
├── UNMET PEER DEPENDENCY redux-devtools-dock-monitor@^1.0.1
├── UNMET PEER DEPENDENCY redux-devtools-log-monitor@^1.0.1
├── UNMET PEER DEPENDENCY redux-thunk@^1.0.3
├── statinamic@0.6.1  extraneous
└── UNMET PEER DEPENDENCY whatwg-fetch@^0.9.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN statinamic@0.6.1 requires a peer of babel-cli@^6.3.17 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-core@^6.3.26 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-loader@^6.2.0 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-plugin-webpack-loaders@^0.2.2 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-preset-es2015@^6.3.13 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-preset-react@^6.3.13 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of babel-preset-react-hmre@^1.0.1 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of cross-env@^1.0.7 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of invariant@^2.1.1 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of react-helmet@^2.1.0 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of react-redux@^4.0.6 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of react-router@^2.0.0-rc6 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of redux@^3.0.0 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of redux-devtools@^3.0.1 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of redux-devtools-dock-monitor@^1.0.1 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of redux-devtools-log-monitor@^1.0.1 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of redux-thunk@^1.0.3 but none was installed.
npm WARN statinamic@0.6.1 requires a peer of whatwg-fetch@^0.9.0 but none was installed.
khoa@khoa-PC-Linux ~/web/test $ cp -R ./node_modules/statinamic/boilerplate/* .
khoa@khoa-PC-Linux ~/web/test $  ./node_modules/.bin/statinamic setup
Installing required dependencies...
pkg: babel-cli@^6.3.17
pkg: babel-core@^6.3.26
pkg: babel-loader@^6.2.0
pkg: babel-plugin-webpack-loaders@^0.2.2
pkg: babel-preset-es2015@^6.3.13
pkg: babel-preset-react@^6.3.13
pkg: babel-preset-react-hmre@^1.0.1
pkg: cross-env@^1.0.7
pkg: invariant@^2.1.1
pkg: react@^0.14.0
pkg: react-dom@^0.14.0
pkg: react-helmet@^2.1.0
pkg: react-redux@^4.0.6
pkg: react-router@^2.0.0-rc6
pkg: redux@^3.0.0
pkg: redux-devtools@^3.0.1
pkg: redux-devtools-dock-monitor@^1.0.1
pkg: redux-devtools-log-monitor@^1.0.1
pkg: redux-thunk@^1.0.3
pkg: webpack@^1.12.1
pkg: whatwg-fetch@^0.9.0
pkg: babel-eslint@^4.1.6
pkg: babel-preset-stage-1@^6.3.13
pkg: css-loader@^0.17.0
pkg: eslint@^1.7.2
pkg: eslint-config-i-am-meticulous@^2.0.0
pkg: eslint-loader@^1.1.0
pkg: eslint-plugin-react@^3.6.2
pkg: extract-text-webpack-plugin@^0.8.2
pkg: file-loader@^0.8.1
pkg: highlight.js@^8.5.0
pkg: json-loader@^0.5.2
pkg: markdown-it@^5.0.0
pkg: markdown-it-toc-and-anchor@^1.0.1
pkg: postcss-browser-reporter@^0.4.0
pkg: postcss-cssnext@^2.4.0
pkg: postcss-loader@^0.7.0
pkg: postcss-reporter@^1.3.0
pkg: raw-loader@^0.5.1
pkg: react-svg-inline@^1.0.1
pkg: style-loader@^0.12.3
pkg: stylelint@^4.0.0
pkg: stylelint-config-standard@^2.0.0
Required dependencies successfully installed.
khoa@khoa-PC-Linux ~/web/test $ npm start

> YOUR-NAME-that-might-be-used-in-some-title-tags@ start /home/khoa/web/test
> cross-env BABEL_ENV=statinamic babel-node scripts/build --server --open --dev

/home/khoa/web/test/node_modules/statinamic/lib/builder/index.js:21
  _fsExtra2.default.emptyDirSync(destination);
                    ^

TypeError: _fsExtra2.default.emptyDirSync is not a function
    at exports.default (/home/khoa/web/test/node_modules/statinamic/lib/builder/index.js:21:21)
    at Object.<anonymous> (build.js:12:1)
    at Module._compile (module.js:398:26)
    at loader (/home/khoa/web/test/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/khoa/web/test/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at /home/khoa/web/test/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/home/khoa/web/test/node_modules/babel-cli/lib/_babel-node.js:162:7)

npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/khoa/.nvm/versions/node/v5.3.0/bin/node" "/home/khoa/.nvm/versions/node/v5.3.0/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! YOUR-NAME-that-might-be-used-in-some-title-tags@ start: `cross-env BABEL_ENV=statinamic babel-node scripts/build --server --open --dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the YOUR-NAME-that-might-be-used-in-some-title-tags@ start script 'cross-env BABEL_ENV=statinamic babel-node scripts/build --server --open --dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the YOUR-NAME-that-might-be-used-in-some-title-tags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=statinamic babel-node scripts/build --server --open --dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs YOUR-NAME-that-might-be-used-in-some-title-tags
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls YOUR-NAME-that-might-be-used-in-some-title-tags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/khoa/web/test/npm-debug.log
```

**Comment by thangngoc89** [comment]
This issue was solved in lastest master. Closed for now
