### ISSUE TITLE
Update deploy.sh in gh-pages.md

### ISSUE THREAD

**Issue by nlarche** [MoOx/statinamic#388]
I think deploy.sh documentation in [ #gh-pages.md](https://github.com/MoOx/statinamic/blob/next/docs/content/docs/usage/gh-pages.md#create-a-script) should be updated with `--dist dist`, without I have this error : 
```path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1251:7)
    at Object.<anonymous> (/usr/lib/node_modules/gh-pages/bin/gh-pages:27:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```
I create a pull request #389

**Comment by MoOx** [comment]
Closed by #389
