### ISSUE TITLE
Error install setup

### ISSUE THREAD

**Issue by magsout** [MoOx/statinamic#44]
```console
npm install statinamic --save-dev
npm run statinamic
```

Error:

```console
> statinamic setup

module.js:338
    throw err;
    ^

Error: Cannot find module 'npm-install-package'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/GuillaumeDEMESY/Github/Me/magsout.github.io/node_modules/statinamic/lib/bin/statinamic-setup.js:5:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

of course, if I install npm-install-package manually, its works

**Comment by MoOx** [comment]
Oups, I forgot to add it as a dep :(
Will do!
